### PR TITLE
Issue #2702667: Cleanup the views row plugin

### PR DESCRIPTION
**Pull request by m4olivei**
Resolves https://www.drupal.org/node/2702667.

### CODE REVIEW

**Comment by m4olivei** [comment]
@steffenr could you give this a look?  I believe you're using the views module right?

**Comment by m4olivei** [comment]
Actually hang on a bit, I'm still working on refining this.

**Comment by m4olivei** [comment]
OK, now it works. I also added in cores concept of have $item_elements, which themes/modules can alter in a preprocessor to add other tags to each item.  For example <description> isn't required, and there isn't a good way to pull that in a general sense, but with this, a module/theme could add that in.

**Comment by scottrigby** [comment]
This looks good to me :+1: But I don't have time to test it Today. Can someone review/test and get back before we merge?

**Comment by scottrigby** [comment]
Also @m4olivei let's hold off before actually merging. @vgardner and I were talking this morning about adding Drupal commit message style attribution inside of our GitHub merge commit messages, so people get credit on d.o for reviewing PRs (not just for the commits themselves). I would like to investigate automating the default GitHub commit message (maybe through a plugin we could add to this repo). We don't need to let that automation idea hold us up, because we can just emulate that manually, but I'd like to try to start doing that ASAP if it's easy enough :smile:

**Comment by m4olivei** [comment]
@scottrigby by manually, do you mean doing the merge locally into `7.x-1.x` with a tailored commit message and then pushing to `7.x-1.x`?

**Comment by scottrigby** [comment]
^ We sorted this out in FB chat :+1:

**Comment by m4olivei** [comment]
@scottrigby and I chatted about this, but just to re-iterate, I've tested with this code and am currently using it on our site.  Working quite nicely.

**Pull request merged**
