### PR TITLE
Issue #2686983: Features integration

### PR DESCRIPTION
**Pull request by m4olivei**
This adds support to export the flag that turns on FB IA opt in per entity + bundle pair.

See https://www.drupal.org/node/2686983

### CODE REVIEW

**Comment by m4olivei** [comment]
I'll rebase this once https://github.com/BurdaMagazinOrg/module-fb_instant_articles/pull/17 gets in.

**Comment by scottrigby** [comment]
@m4olivei reminder to rebase now that #17 has been merged :smile: 

I would remove the update hook though, since we're still in very active development before any release has been made. After we issue releases, this would be important :) Otherwise I think this is a good idea to add.

Another note is that while we allow entity type configuration, a lot of the current code only supports nodes. This is something we can take up in a later issue, but I want to mention it here for conversation sake since you're refactoring the storage of that setting in this PR.

**Comment by m4olivei** [comment]
@scottrigby yep yep, I did the rebase.  Yeah, good call on the update hook, I was in the wrong mindset when I wrote that up, I'll remove it.

Agreed regarding entity_type config. I keep coming across stuff called 'entity_type' but not really supporting anything but nodes.  Definitely could be a follow up down the road.  It would probably need someone who actually has a use case outside of nodes to be motivated to write it.

**Comment by m4olivei** [comment]
Update hook removed, should be good to go.

**Comment by m4olivei** [comment]
@scottrigby does this still look good to you?  Would be nice to have this, it's one less thing I have to do to get my test environment setup.

**Pull request merged**
