### PR TITLE
Issue #2872807 Manage creation and rendering of InstantArticle object via the Serialization API

### PR DESCRIPTION
**Pull request by m4olivei**
This PR introduces Normalizers and an Encoder to integrated the FBIA PHP SDK with the Drupal Serialzation API. It allows you to programatically load a node, pipe it through the serialization API, and get FBIA markup out the other end. As an argument you pass an EntityViewDisplay object as a mapping to guide the process.

In order to manually test:

* Enable `fb_instant_articles` module
* Enable Facebook Instant Articles support on one of your content types (eg. `/admin/structure/types/manage/article`).
* Configure the `fb_instant_articles` view mode (eg. `/admin/structure/types/manage/article/display/fb_instant_articles`) by putting fields into regions and assigning FBIA prefixed field formatters.
* Open up a PHP interpreter using `drush php` and enter the following:

```
>>> \Drupal::service('serializer')->serialize(\Drupal\node\Entity\Node::load(1), 'fbia', ['entity_view_display' => \Drupal::entityTypeManager()->getStorage('entity_view_display')->load('node.article.fb_instant_articles')]);
```
This invokes the `serialize` method on the `serializer` service, passing in a node object (nid 1), the format (`fbia`) and the EntityViewDisplay object. This may differ slightly for your own local setup.

Also run the test suite to verify that everything is green, eg.

```
$ cd core
$ ../vendor/bin/phpunit --verbose --debug --group=fb_instant_articles
```

### CODE REVIEW

**Comment by juampynr** [comment]
Just read the code and it looks fine to me.

While doing a manual test locally, I found these JS errors when I tried to set the formatter:

image

Here is the full error from the first one:

```
"
An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /admin/structure/types/manage/article/display/fb_instant_articles?ajax_form=1
StatusText: OK
ResponseText: 
( ! ) Fatal error: Class 'Facebook\InstantArticles\Transformer\Transformer' not found in /var/www/draco/web/modules/custom/module-fb_instant_articles/src/Transformer.php on line 10
Call Stack
#TimeMemoryFunctionLocation
10.0007385840{main}(  ).../index.php:0
20.0017494144Drupal\Core\DrupalKernel->handle(  ).../index.php:19
30.00821482184Stack\StackedHttpKernel->handle(  ).../DrupalKernel.php:656
40.00821482184Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(  ).../StackedHttpKernel.php:23
50.00821482184Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(  ).../NegotiationMiddleware.php:50
60.00821482184Drupal\page_cache\StackMiddleware\PageCache->handle(  ).../ReverseProxyMiddleware.php:47
70.00821482184Drupal\page_cache\StackMiddleware\PageCache->pass(  ).../PageCache.php:78
80.00821482184Drupal\Core\StackMiddleware\KernelPreHandle->handle(  ).../PageCache.php:99
90.01021923768Drupal\Core\StackMiddleware\Session->handle(  ).../KernelPreHandle.php:47
100.01182026152Symfony\Component\HttpKernel\HttpKernel->handle(  ).../Session.php:57
110.01182026568Symfony\Component\HttpKernel\HttpKernel->handleRaw(  ).../HttpKernel.php:64
120.03625070584call_user_func_array:{/var/www/draco/web/vendor/symfony/http-kernel/HttpKernel.php:144}
(  ).../HttpKernel.php:144
130.03625070648Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}(  ).../HttpKernel.php:144
140.03625070648Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(  ).../EarlyRenderingControllerWrapperSubscriber.php:97
150.03625073184Drupal\Core\Render\Renderer->executeInRenderContext(  ).../EarlyRenderingControllerWrapperSubscriber.php:124
160.03635073576Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}(  ).../Renderer.php:574
170.03635073576call_user_func_array:{/var/www/draco/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php:123}
(  ).../EarlyRenderingControllerWrapperSubscriber.php:123
180.03635073984Drupal\Core\Controller\FormController->getContentResult(  ).../EarlyRenderingControllerWrapperSubscriber.php:123
190.03805400904Drupal\Core\Form\FormBuilder->buildForm(  ).../FormController.php:74
200.04676725952Drupal\Core\Form\FormBuilder->processForm(  ).../FormBuilder.php:314
210.05367036320Drupal\Core\Form\FormBuilder->rebuildForm(  ).../FormBuilder.php:621
220.05367036320Drupal\Core\Form\FormBuilder->retrieveForm(  ).../FormBuilder.php:364
230.05367038576call_user_func_array:{/var/www/draco/web/core/lib/Drupal/Core/Form/FormBuilder.php:514}
(  ).../FormBuilder.php:514
240.05367038984Drupal\Core\Entity\EntityForm->buildForm(  ).../FormBuilder.php:514
250.05377040632Drupal\field_ui\Form\EntityDisplayFormBase->form(  ).../EntityForm.php:115
260.05387047688Drupal\field_ui\Form\EntityViewDisplayEditForm->buildFieldRow(  ).../EntityDisplayFormBase.php:187
270.05387047688Drupal\field_ui\Form\EntityDisplayFormBase->buildFieldRow(  ).../EntityViewDisplayEditForm.php:36
280.05407056928Drupal\Core\Entity\Entity\EntityViewDisplay->getRenderer(  ).../EntityDisplayFormBase.php:343
290.05407057304Drupal\Core\Field\FormatterPluginManager->getInstance(  ).../EntityViewDisplay.php:201
300.05407057680Drupal\Core\Field\FormatterPluginManager->createInstance(  ).../FormatterPluginManager.php:126
310.05407057680Drupal\fb_instant_articles\Plugin\Field\FieldFormatter\TransformerFormatter::create(  ).../FormatterPluginManager.php:64
320.05407058000Drupal\Component\DependencyInjection\Container->get(  ).../TransformerFormatter.php:71
330.05407060624Drupal\Component\DependencyInjection\Container->createService(  ).../Container.php:177
340.05457063424spl_autoload_call
(  ).../Container.php:268
350.05457063568Composer\Autoload\ClassLoader->loadClass(  ).../Container.php:268
360.05457063680Composer\Autoload\includeFile(  ).../ClassLoader.php:322
370.05467064680include( '/var/www/draco/web/modules/custom/module-fb_instant_articles/src/Transformer.php' ).../ClassLoader.php:444
"
```

The transform class does not seem to be part of the module. Am I missing anything?

**Comment by m4olivei** [comment]
@juampynr yeah, the module has a composer dependency, you need to install the dependency and then it should work.

**Comment by juampynr** [comment]
Thanks, looks good although I got some weird debugging output:

```
>>> \Drupal::service('serializer')->serialize(\Drupal\node\Entity\Node::load(1), 'fbia', ['entity_view_display' => \Drupal::entityTypeManager()->getStorage('entity_view_display')->load('node.article.fb_instant_articles')]);
DEBUG - ===========================
DEBUG - 
DEBUG - ===========================
DEBUG - <html>
<head><meta charset="utf-8"></head>
<body><p>Sample article body</p></body>
</html>
DEBUG - ===========================
DEBUG - <head><meta charset="utf-8"></head>

DEBUG - ===========================
DEBUG - <meta charset="utf-8">
DEBUG - context class: Facebook\InstantArticles\Elements\InstantArticle
DEBUG - node name: meta
DEBUG - CONTENT NOT MATCHED: 
<meta charset="utf-8"/>
DEBUG - ===========================
DEBUG - <body><p>Sample article body</p></body>
DEBUG - ===========================
DEBUG - <p>Sample article body</p>
DEBUG - ===========================
DEBUG - Sample article body
=> "<!doctype html><html><head><link rel="canonical" href="http://default/node/1"/><meta charset="utf-8"/><meta property="op:generator" content="facebook-instant-articles-sdk-php"/><meta property="op:generator:version" content="1.6.1"/><meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/><meta property="op:generator:transformer:version" content="1.6.1"/><meta property="op:markup_version" content="v1.0"/></head><body><article><header><h1>Sample title</h1><time class="op-published" datetime="2017-06-21T07:49:53+00:00">June 21st, 7:49am</time><time class="op-modified" datetime="2017-06-21T07:50:23+00:00">June 21st, 7:50am</time><address><a>admin</a></address></header><p>Sample article body</p><figure><img src="http://default/sites/default/files/2017-06/totoro.jpg"/></figure></article></body></html>"
```

@m4olivei  I had to manually install the Serialization module in order to use the Serializer service. Shouldn't it be a dependency of this module. If so, remember to add a database update too.

Apart from the serialization dependency, I think that this is good to go. cc @bgbohling.

**Comment by m4olivei** [comment]
@juampynr thanks!

I've added the serialization dependency. No need for an update hook, the Drupal 8 version of the module on the 2.x branch doesn't have a release yet, and we've made no claims to supporting any update path (the 1.x version of the branch is incomplete and never got a full release).

**Pull request merged**
