### PR TITLE
Migrate and merge modules

### PR DESCRIPTION
**Pull request by simonengelhardt**
@vgardner and @steffenr have [worked together](https://www.drupal.org/node/2690803) on merging the modules and have [given the go](https://www.facebook.com/groups/1030797546992409/permalink/1031853190220178/?comment_id=1035090759896421&comment_tracking=%7B%22tn%22%3A%22R%22%7D) to migrate the module code to GitHub, so I am hereby doing that.

We are unifying the two Instant Articles Drupal modules into the [fb_instant_articles](https://www.drupal.org/project/fb_instant_articles) namespace and the code hosting to [this GitHub repo](https://github.com/BurdaMagazinOrg/module-facebook_instant_articles).

This pull request migrates all code as of the [latest commit](http://cgit.drupalcode.org/fb_instant_articles/commit/?id=ef58d1caac6b831f5f3bdf8abc43ebbe498daef3) from the 7.1-1.x branch of http://cgit.drupalcode.org/fb_instant_articles to the 7.x-1.x branch of this GitHub repo.

### CODE REVIEW

**Comment by scottrigby** [comment]
So guys, are you planning to next change the namespace of this repo from `BurdaMagazinOrg/module-facebook_instant_articles` to `BurdaMagazinOrg/fb_instant_articles`? I've gone through that process with other GitHub repos and it's pretty painless (though there is a small amount of work to do with forks, but I'm happy to help if we get there).

**Comment by scottrigby** [comment]
Also, @dbosen do you have any CI set up to integrate any of your GitHub repos with the Drupal.org-hosted repo for their equivalent module? I have used some services like Jon Pugh's (now defunct? will have to ask him) HubDrop, but also have set up this on our own via GitHub webhooks and GH Jenkins plugin. I'd also be happy to set that up if that's of interest (again, unless you have something like that already going), so that changes made to GitHub are automatically synced to the d.o repo.

**Comment by chrfritsch** [comment]
Thank you guys. I've renamed the repo now, merged your PR and added Vin and Steffen to the FIA Maintainer team

**Comment by dbosen** [comment]
Hi Scott,

we usually do the repo sync manually, but I think, that this is not a good
idea under these circumstances. If you have a working set up for this,
please feel free to implement it!

Daniel

2016-03-24 2:33 GMT+01:00 Scott Rigby notifications@github.com:

**Pull request merged**
