### PR TITLE
Issue #2711165: DOMDocument LoadHTML Bug.

### PR DESCRIPTION
**Pull request by sadiefp**
Resolves https://www.drupal.org/node/2711165 for sites on Acquia servers.

### CODE REVIEW

**Comment by scottrigby** [comment]
@sadiefp Hi thanks for this! Apologies for letting these linger here. 

Can someone else on Acquia hosting verify this? Although we did for many years, I am no longer on any projects hosted there.

**Comment by scottrigby** [comment]
@sadiefp NM, I see this was verified by @Bladedu in this [d.o issue comment](https://www.drupal.org/node/2711165#comment-11795128).

**Comment by sadiefp** [comment]
@scottrigby - not sure how many people need to confirm, but one person on d.o confirmed the patch worked for them: https://www.drupal.org/node/2711165#comment-11795128

**Comment by scottrigby** [comment]
Jinx 😄 Merging

**Pull request merged**
